using Newtonsoft.Json;

namespace Api.Model
{
    /// <summary>
    /// Access token request model
    /// </summary>
    public class AccessTokenRequest
    {
        /// <summary>
        /// Required. The client ID received from GitHub in the app account settings
        /// </summary>
        [JsonProperty("client_id")]
        public string ClientId { get; set; }

        /// <summary>
        /// Required. The client secret received from GitHub in the ap account settings
        /// </summary>
        [JsonProperty("client_secret")]
        public string ClientSecret { get; set; }

        /// <summary>
        /// Required. The code received from the GitHHub login/auth page.
        /// Must be sent from the client app
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; }

        /// <summary>
        /// The passcode generated by this API when generating the login URL
        /// </summary>
        [JsonProperty("state")]
        public string State { get; set; }
    }
}
